apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Backend/backend-deployment.yml
  - Backend/backend-service.yml
  - Frontend/frontend-deployment.yml
  - Frontend/frontend-service.yml
  - Frontend/frontend-ingress.yml
  - Database/db-deployment.yml
  - Database/db-service.yml
  - configmap.yml
  - secrets.yml
